name: FreeTrial
version: '${project.version}'
main: cubeshine.freetrial.FreeTrial
api-version: "1.20"
commands:
  trial:
    aliases: trial
  time:
    aliases: timeleft
permissions:
  freetrial.use:
    default: op