name: FreeTrial
version: '${project.version}'
main: cubeshine.freetrial.FreeTrial
api-version: "1.20"
softdepend: [PlaceholderAPI]
commands:
  trial:
    aliases: trial
  pass:
    aliases: pass
  time:
    aliases: timeleft
permissions:
  freetrial.use:
    default: op